-- Tabla usuarios
CREATE TABLE IF NOT EXISTS usuarios (
  GAFETE TEXT PRIMARY KEY,
  NOMBRE TEXT,
  DEPARTAMENTO TEXT,
  RUTA_MAQUINA TEXT,
  TIPO_USUARIO TEXT
);

-- Tabla cables
CREATE TABLE IF NOT EXISTS cables (
  LCODE TEXT PRIMARY KEY,
  LINEA TEXT,
  CIRCUITO TEXT,
  COLOR TEXT,
  MAQUINA_CORTE TEXT,
  RUTA_CORTE TEXT,
  DESTINO TEXT,
  VOLUMEN_DIARIO TEXT,
  MAXIMO TEXT,
  MINIMO TEXT
);

-- Tabla disparos
CREATE TABLE IF NOT EXISTS disparos (
  id SERIAL PRIMARY KEY,
  LINEA TEXT,
  LCODE TEXT,
  CIRCUITO TEXT,
  COLOR TEXT,
  MAQUINA_CORTE TEXT,
  RUTA_CORTE TEXT,
  DESTINO TEXT,
  VOLUMEN_DIARIO TEXT,
  MAXIMO TEXT,
  MINIMO TEXT,
  PIEZAS_RESTANTES TEXT,
  FECHA TEXT,
  ESTATUS TEXT
);

-- Tabla historial
CREATE TABLE IF NOT EXISTS historial (
  id SERIAL PRIMARY KEY,
  LINEA TEXT,
  LCODE TEXT,
  CIRCUITO TEXT,
  COLOR TEXT,
  MAQUINA_CORTE TEXT,
  RUTA_CORTE TEXT,
  DESTINO TEXT,
  VOLUMEN_DIARIO TEXT,
  MAXIMO TEXT,
  MINIMO TEXT,
  PIEZAS_RESTANTES TEXT,
  FECHA TEXT,
  ESTATUS TEXT,
  GAFETE TEXT
);